Repository simonadamgyula/Git-projekt2, pull requests merged in 2023-01, with the labels that each got.

#2 névsor rendben
  README.md
Labels: documentation

#4 kerékpárok elmentve
  Források/KTM1.jpg
  Források/KTM2.jpg
Labels: enhancement

#8 javítás készen
  README.md
Labels: bug
